---
- name: Load distro-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "os_{{ ansible_lsb.codename }}_{{ ansible_architecture }}.yml"
    - "os_{{ ansible_distribution_release }}.yml"
    - "os_default.yml"

- name: Install nginx packages
  apt:
    state: latest
    name:
      - nginx-full
      - apache2-utils

- name: Install PHP Basics
  apt:
    state: latest
    name:
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-json"
      # https://varunver.wordpress.com/2019/10/11/install-php-mcrypt-on-debian-10-php-7-3/
      #- "php{{ php_version }}-mcrypt"
      - "php{{ php_version }}-gd"
      - "{{ php_apcu }}"
      - php-geoip

- name: Create nginx cert directory
  file: path=/etc/nginx/ssl state=directory owner=root group=www-data mode=0750

- include: acme.yml
  tags: acme
  when: httpd_lets_encrypt

- name: Create nginx cert files
  shell: >
    umask 0027 && openssl req -newkey rsa:2048 -nodes -x509 -days 3650 -subj "{{ httpd_cert_subj }}{{ httpd_domain }}" -keyout {{ httpd_domain }}.key -out {{ httpd_domain }}.pem -extensions v3_ca
  args:
    chdir: /etc/nginx/ssl
    creates: /etc/nginx/ssl/{{ httpd_domain }}.pem
  when: not httpd_lets_encrypt

- name: Create nginx dhparam file
  command: openssl dhparam -out dhparam.pem 2048
  args:
    chdir: /etc/nginx/ssl
    creates: /etc/nginx/ssl/dhparam.pem

- name: Fix SSL cert permissions
  file: dest=/etc/nginx/ssl owner=root group=www-data mode=g=rX,o= recurse=yes

- name: Create nginx root directory
  file: path=/var/www/html state=directory owner=root group=www-data mode=0750

- name: Render default documents
  copy: src={{ item }} dest=/var/www/html/{{ item }} owner=root group=www-data mode=0640 force=yes
  with_items:
    - 50x.html
