---
- name: Render /etc/motd
  template: src=motd.j2 dest=/etc/motd owner=root group=root mode=0644 force=yes

#- name: Link /etc/motd.head
#  file: src=motd dest=/etc/motd.head state=link owner=root group=root force=yes

- name: Copy Superuser Helper Scripts
  copy: src={{ item }} dest=/usr/local/sbin/{{ item }} owner=root group=root mode=0750
  with_items:
    - load-domain-certificate

- name: Install Host Configuration Files
  copy: src={{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - profile.d/aliases.sh
    - tmux.conf

- name: Install Some Essentials
  apt: name={{ item }} state=latest
  with_items:
    - bash-completion
    - bc
    - bind9-host
    - bzip2
    - cfv
    - colordiff
    - curl
    - gawk
    - haveged
    - htop
    - httpie
    - inxi
    - iotop
    - lftp
    - libxml2-utils
    - links
    - lsb-release
    - lsof
    - mediainfo
    - ncdu
    - ntp
    - parallel
    - p7zip-full
    - psmisc
    - python-virtualenv
    - realpath
    - rsync
    - sysstat
    - sudo
    - tmux
    - unzip
    - vim
    - vnstat
    - wget
    - zip

- name: Install Recent Essentials
  apt: name={{ item }} state=latest
  with_items:
    - lnav
  when: ansible_distribution != "Debian" or ansible_distribution_major_version not in "67"
